DOMAIN = "seneye"

CONF_UPDATE_INTERVAL_MIN = "update_interval_min"
CONF_TEMP_OFFSET = "temp_offset"
CONF_PH_OFFSET = "ph_offset"
CONF_PAR_SCALE = "par_scale"

DEFAULT_UPDATE_INTERVAL_MIN = 5
DEFAULT_TEMP_OFFSET = 0.0
DEFAULT_PH_OFFSET = 0.0
DEFAULT_PAR_SCALE = 1.0
